"""buidl CLI: `python -m buidl run ...` (brief -> product) and `python -m buidl promote ...` (sandbox branch -> real repo)."""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

from . import brief as brief_mod
from . import catalog, grok, plan as plan_mod, publish
from .generate import generate, run as run_cmd

OWNER = publish.OWNER


def log(msg: str) -> None:
    print(f"[buidl {dt.datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def pick_mode(mode: str) -> str:
    if mode != "auto":
        return mode
    if os.environ.get("FORGE_TOKEN"):
        return "create"
    if os.environ.get("GITHUB_ACTIONS"):
        return "branch"
    return "none"


def cmd_run(a: argparse.Namespace) -> int:
    t0 = time.time()
    result: dict = {"started_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"), "status": "running", "steps": {}}
    out_json = Path(a.result)

    def save():
        result["elapsed_s"] = round(time.time() - t0)
        result["grok_usage"] = grok.USAGE.summary()
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(result, indent=2))

    try:
        mode = pick_mode(a.mode)
        result["mode"] = mode
        text = Path(a.brief_file).read_text() if a.brief_file else (a.brief_text or "")
        if a.requirements:
            req = json.loads(Path(a.requirements).read_text())
            log(f"requirements from {a.requirements}")
        else:
            b = brief_mod.load(a.brief_url, text)
            log(f"brief loaded: {b['chars']} chars from {b['sources'] or 'pasted text'}")
            req = brief_mod.parse(b)
        result["steps"]["parse"] = {"program": req.get("program"), "kind": req.get("kind"), "tracks": len(req.get("tracks", [])), "criteria": len(req.get("judging_criteria", []))}
        log(f"parsed: {req.get('program')} ({req.get('kind')}), {len(req.get('tracks', []))} tracks"); save()

        cat = catalog.load()
        short = catalog.shortlist(cat, req)
        result["steps"]["catalog"] = {k: len(cat[k]) for k in ("hub", "index", "grokhack", "starters")} | {"errors": cat["errors"]}
        if a.plan:
            pl = plan_mod.normalise(json.loads(Path(a.plan).read_text()), cat, a.name)
        else:
            pl = plan_mod.make_plan(req, short, cat, a.name)
        slug = pl["slug"]
        result["slug"] = slug
        result["steps"]["plan"] = {"title": pl.get("title"), "contract": pl["contract"]["name"], "chain": pl["chain"]["name"], "tracks": [t.get("track") for t in pl.get("target_tracks", [])],
                                   "blocks": [b["ref"] for b in pl["bill_of_blocks"]], "unverified_dropped": [b.get("ref") for b in pl.get("unverified_blocks", [])]}
        log(f"plan: {pl.get('title')} -> {slug}, {len(pl['bill_of_blocks'])} blocks"); save()
        out_json.with_suffix(".plan.json").write_text(json.dumps(pl, indent=2))
        out_json.with_suffix(".requirements.json").write_text(json.dumps(req, indent=2))

        host = os.environ.get("GITHUB_REPOSITORY", f"{OWNER}/buidl")
        if mode == "branch":
            repo_url, ref = f"https://github.com/{host}", f"product/{slug}"
            owner, name = host.split("/")
            pages_url = f"https://{owner.lower()}.github.io/{name}/p/{slug}/"
        else:
            repo_url, ref, pages_url = f"https://github.com/{OWNER}/{slug}", "main", f"https://{OWNER.lower()}.github.io/{slug}/"
        out = Path(a.out or f"/tmp/buidl/{slug}")
        gen = generate(out, req, pl, repo_url=repo_url, pages_url=pages_url, ref=ref, use_grok=not a.no_grok)
        result["steps"]["generate"] = gen
        log(f"generated {out} (contract {gen['contract']['name']} from {gen['contract']['source']}, {len(gen['contract']['attempts'])} grok attempts)"); save()

        code, ci_out = run_cmd(["bash", "scripts/ci.sh"], out, timeout=900)
        result["steps"]["local_ci"] = {"ok": code == 0, "tail": ci_out[-1500:]}
        if code:
            raise RuntimeError("local CI failed:\n" + ci_out[-3000:])
        log("local CI green"); save()
        for junk in ("contracts/out", "contracts/cache", "web/node_modules", "web/dist", "web/public/contracts"):
            shutil.rmtree(out / junk, ignore_errors=True)

        if mode == "none":
            result["status"] = "success"
            result["note"] = "generated + tested locally only (mode none)"
        elif mode == "create":
            env = {"GH_TOKEN": os.environ["FORGE_TOKEN"]} if os.environ.get("FORGE_TOKEN") else None
            pub = publish.publish_create(out, slug, f"{pl.get('title')}: {pl.get('tagline', '')} (generated by Blockchains/buidl)", env)
            result["publish"] = pub
            result["status"] = "success" if pub["ok"] else "failed"
        else:
            pub = publish.publish_branch(out, slug, host, a.nonce or f"{slug}-{int(time.time())}")
            result["publish"] = pub
            result["status"] = "success" if pub["ok"] else "failed"
        log(f"status: {result['status']}")
    except Exception as e:
        result["status"] = "failed"
        result["error"] = f"{type(e).__name__}: {e}"[:4000]
        log(result["error"])
    save()
    return 0 if result["status"] == "success" else 1


URL_FILES = (".md", ".json", ".txt", ".yml", ".html", ".js")


def cmd_promote(a: argparse.Namespace) -> int:
    """Turn sandbox branch product/<slug> of the pipeline repo into its own repo Blockchains/<slug> (needs gh or FORGE_TOKEN)."""
    host, slug = a.host, a.slug
    work = Path(f"/tmp/buidl-promote/{slug}")
    shutil.rmtree(work, ignore_errors=True)
    work.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "clone", "-q", "--depth", "1", "-b", f"product/{slug}", f"https://github.com/{host}.git", str(work)], check=True)
    shutil.rmtree(work / ".git")
    if (work / ".buidl" / "workflows").exists():
        (work / ".github").mkdir(exist_ok=True)
        shutil.move(str(work / ".buidl" / "workflows"), work / ".github" / "workflows")
        shutil.rmtree(work / ".buidl", ignore_errors=True)
    owner, name = host.split("/")
    pairs = [(f"https://github.com/{host}/blob/product/{slug}", f"https://github.com/{OWNER}/{slug}/blob/main"),
             (f"https://github.com/{host}/tree/product/{slug}", f"https://github.com/{OWNER}/{slug}"),
             (f"https://{owner.lower()}.github.io/{name}/p/{slug}/", f"https://{OWNER.lower()}.github.io/{slug}/"),
             (f'"repo_url": "https://github.com/{host}"', f'"repo_url": "https://github.com/{OWNER}/{slug}"'),
             (f'"repo": "{host}"', f'"repo": "{OWNER}/{slug}"'),
             (f"Repo: https://github.com/{host}\n", f"Repo: https://github.com/{OWNER}/{slug}\n")]
    for p in work.rglob("*"):
        if p.is_file() and p.suffix in URL_FILES and "contracts/lib" not in str(p) and "node_modules" not in str(p):
            s = p.read_text(errors="ignore")
            s2 = s
            for x, y in pairs:
                s2 = s2.replace(x, y)
            if p.name == "README.md" and p.parent == work and "actions/workflows/ci.yml/badge.svg" not in s2:
                lines = s2.split("\n", 1)
                badge = (f"\n[![CI](https://github.com/{OWNER}/{slug}/actions/workflows/ci.yml/badge.svg)](https://github.com/{OWNER}/{slug}/actions/workflows/ci.yml) "
                         f"[![Pages](https://github.com/{OWNER}/{slug}/actions/workflows/pages.yml/badge.svg)](https://{OWNER.lower()}.github.io/{slug}/)\n")
                s2 = lines[0] + "\n" + badge + (lines[1] if len(lines) > 1 else "")
            if s2 != s:
                p.write_text(s2)
    meta = json.loads((work / "buidl.json").read_text())
    meta["promoted_from"] = f"{host}@product/{slug}"
    (work / "buidl.json").write_text(json.dumps(meta, indent=2))
    code, out = run_cmd(["bash", "scripts/ci.sh"], work, timeout=900)
    if code:
        print(out[-3000:])
        return 1
    for junk in ("contracts/out", "contracts/cache", "web/node_modules", "web/dist", "web/public/contracts"):
        shutil.rmtree(work / junk, ignore_errors=True)
    plan = json.loads((work / "brief" / "plan.json").read_text())
    env = {"GH_TOKEN": os.environ["FORGE_TOKEN"]} if os.environ.get("FORGE_TOKEN") else None
    pub = publish.publish_create(work, slug, f"{plan.get('title')}: {plan.get('tagline', '')} (generated by Blockchains/buidl)", env)
    Path(a.result).parent.mkdir(parents=True, exist_ok=True)
    Path(a.result).write_text(json.dumps(pub, indent=2))
    print(json.dumps({k: pub[k] for k in ("repo_url", "pages_url", "ok")}))
    return 0 if pub["ok"] else 1


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="buidl")
    sp = ap.add_subparsers(dest="cmd", required=True)
    r = sp.add_parser("run", help="brief -> product")
    r.add_argument("--brief-url", help="one or more URLs (space/comma separated)")
    r.add_argument("--brief-text", help="pasted brief text")
    r.add_argument("--brief-file", help="file with pasted brief text")
    r.add_argument("--requirements", help="skip parsing: use this requirements.json")
    r.add_argument("--plan", help="skip planning: use this plan.json")
    r.add_argument("--name", help="repo/slug name (default: chosen by the planner)")
    r.add_argument("--mode", default="auto", choices=["auto", "create", "branch", "none"])
    r.add_argument("--out", help="output dir (default /tmp/buidl/<slug>)")
    r.add_argument("--result", default="result.json")
    r.add_argument("--nonce", help="correlation id for dispatched workflows")
    r.add_argument("--no-grok", action="store_true", help="template contract + docs (CI self-test)")
    r.set_defaults(fn=cmd_run)
    p = sp.add_parser("promote", help="sandbox branch -> standalone repo")
    p.add_argument("slug")
    p.add_argument("--host", default=f"{OWNER}/buidl")
    p.add_argument("--result", default="promote.json")
    p.set_defaults(fn=cmd_promote)
    a = ap.parse_args(argv)
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
